### 我相信，在日常工作中，各位会更多的面对excel这种类型的表格数据
### 所以下面我想和大家分享:
#### 如何从excel文件读取数据和如何将pandas中的DataFrame类型的数据保存在excel文件中

In [1]:
import numpy as np
import pandas as pd

- 如何向excel文件写入DataFrame数据
    - 安装xlsxwriter作为读取引擎:pip install xlsxwriter
    - 编写代码

In [2]:
excel_writer = pd.ExcelWriter(path='sample.xlsx',engine='xlsxwriter')
df = pd.DataFrame(np.random.randn(12,6),columns=list('ABCDEF'))
df.to_excel(excel_writer,sheet_name='第一页啊')
excel_writer.save()

- 如何从excel文件读取数据
    - 安装指定版本的xlrd:pip install xlrd==1.2.0
    - 编写代码

In [3]:
df = pd.read_excel('sample.xlsx')
df

    Unnamed: 0         A         B         C         D         E         F
0            0  0.438263  0.692700  2.143731  0.386463 -0.884741 -2.080132
1            1  0.947938  1.221729  1.213840 -0.864949 -1.221588  0.458906
2            2  1.851955  0.262832 -0.971728 -0.449051  1.592155  0.210833
3            3 -0.234564 -1.233367 -0.622671  0.964902 -0.957392 -2.016878
4            4 -0.289272 -0.918242  0.908245 -0.663367  1.061497 -0.688399
5            5  1.202629  0.391999 -0.115621  0.229527  0.140617  0.349877
6            6 -0.884854  0.667709 -2.308511 -0.243656 -1.318741 -1.845275
7            7 -0.870994 -0.038424 -1.267668 -0.012599 -1.460464 -0.485436
8            8  0.945406  0.511407  2.384546  0.644355 -1.750740 -0.046388
9            9  1.703105  0.050988  1.106764 -2.106215  0.924204  1.169866
10          10 -0.694270  1.427593 -0.235261 -0.952733 -0.845942 -0.362628
11          11 -1.762510 -1.852246 -0.314689  0.451147 -0.437045  1.484851